title: Intelligent Loan Underwriting (ILOUL)
description: AI Agent Capabilities for Financial Services Workflows

# Use GitHub's built-in theme
theme: minima

# Enable plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
